export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const GET_USERS = "GET_USERS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const USER_UPDATED = "USER_UPDATED";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const FILTER_CUSTOMER = "FILTER_CUSTOMER";

export const GET_SUPPLIER = "GET_SUPPLIER";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const SET_CURRENT_SUPPLIER = "SET_CURRENT_SUPPLIER";
export const CLEAR_SUPPLIER = "CLEAR_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const SUPPLIER_ERROR = "SUPPLIER_ERROR";
export const FILTER_SUPPLIER = "FILTER_SUPPLIER";

export const GET_CITY = "GET_CITY";
export const GET_CITIES = "GET_CITIES";
export const ADD_CITY = "ADD_CITY";
export const UPDATE_CITY = "UPDATE_CITY";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const CLEAR_CITY = "CLEAR_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const CITY_ERROR = "CITY_ERROR";
export const FILTER_CITY = "FILTER_CITY";
export const POPULATE_CITIES = "POPULATE_CITIES";

export const GET_ITEM = "GET_ITEM";
export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_ITEM = "CLEAR_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEM_ERROR = "ITEM_ERROR";
export const FILTER_ITEM = "FILTER_ITEM";

export const GET_UOM = "GET_UOM";
export const GET_UOMS = "GET_UOMS";
export const ADD_UOM = "ADD_UOM";
export const UPDATE_UOM = "UPDATE_UOM";
export const SET_CURRENT_UOM = "SET_CURRENT_UOM";
export const CLEAR_UOM = "CLEAR_UOM";
export const DELETE_UOM = "DELETE_UOM";
export const UOM_ERROR = "UOM_ERROR";
export const FILTER_UOM = "FILTER_UOM";

export const GET_CUSTOMER_ENQUIRY = "GET_CUSTOMER_ENQUIRY";
export const GET_CUSTOMER_ENQUIRIES = "GET_CUSTOMER_ENQUIRIES";
export const ADD_CUSTOMER_ENQUIRY = "ADD_CUSTOMER_ENQUIRY";
export const UPDATE_CUSTOMER_ENQUIRY = "UPDATE_CUSTOMER_ENQUIRY";
export const SET_CURRENT_CUSTOMER_ENQUIRY = "SET_CURRENT_CUSTOMER_ENQUIRY";
export const CLEAR_CUSTOMER_ENQUIRY = "CLEAR_CUSTOMER_ENQUIRY";
export const DELETE_CUSTOMER_ENQUIRY = "DELETE_CUSTOMER_ENQUIRY";
export const CUSTOMER_ENQUIRY_ERROR = "CUSTOMER_ENQUIRY_ERROR";
export const FILTER_CUSTOMER_ENQUIRY = "FILTER_CUSTOMER_ENQUIRY";

export const GET_CUSTOMER_DELIVERY = "GET_CUSTOMER_DELIVERY";
export const GET_CUSTOMER_DELIVERIES = "GET_CUSTOMER_DELIVERIES";
export const ADD_CUSTOMER_DELIVERY = "ADD_CUSTOMER_DELIVERY";
export const UPDATE_CUSTOMER_DELIVERY = "UPDATE_CUSTOMER_DELIVERY";
export const SET_CURRENT_CUSTOMER_DELIVERY = "SET_CURRENT_CUSTOMER_DELIVERY";
export const CLEAR_CUSTOMER_DELIVERY = "CLEAR_CUSTOMER_DELIVERY";
export const DELETE_CUSTOMER_DELIVERY = "DELETE_CUSTOMER_DELIVERY";
export const CUSTOMER_DELIVERY_ERROR = "CUSTOMER_DELIVERY_ERROR";
export const FILTER_CUSTOMER_DELIVERY = "FILTER_CUSTOMER_DELIVERY";

export const GET_CUSTOMER_PAYMENT = "GET_CUSTOMER_PAYMENT";
export const GET_CUSTOMER_PAYMENTS = "GET_CUSTOMER_PAYMENTS";
export const ADD_CUSTOMER_PAYMENT = "ADD_CUSTOMER_PAYMENT";
export const UPDATE_CUSTOMER_PAYMENT = "UPDATE_CUSTOMER_PAYMENT";
export const SET_CURRENT_CUSTOMER_PAYMENT = "SET_CURRENT_CUSTOMER_PAYMENT";
export const CLEAR_CUSTOMER_PAYMENT = "CLEAR_CUSTOMER_PAYMENT";
export const DELETE_CUSTOMER_PAYMENT = "DELETE_CUSTOMER_PAYMENT";
export const CUSTOMER_PAYMENT_ERROR = "CUSTOMER_PAYMENT_ERROR";
export const FILTER_CUSTOMER_PAYMENT = "FILTER_CUSTOMER_PAYMENT";
export const TOTAL_RECEIVABLE = "TOTAL_RECEIVABLE";

export const GET_PURCHASE = "GET_PURCHASE";
export const GET_PURCHASES = "GET_PURCHASES";
export const ADD_PURCHASE = "ADD_PURCHASE";
export const UPDATE_PURCHASE = "UPDATE_PURCHASE";
export const SET_CURRENT_PURCHASE = "SET_CURRENT_PURCHASE";
export const CLEAR_PURCHASE = "CLEAR_PURCHASE";
export const DELETE_PURCHASE = "DELETE_PURCHASE";
export const PURCHASE_ERROR = "PURCHASE_ERROR";
export const FILTER_PURCHASE = "FILTER_PURCHASE";

export const GET_SUPPLIER_PAYMENT = "GET_SUPPLIER_PAYMENT";
export const GET_SUPPLIER_PAYMENTS = "GET_SUPPLIER_PAYMENTS";
export const ADD_SUPPLIER_PAYMENT = "ADD_SUPPLIER_PAYMENT";
export const UPDATE_SUPPLIER_PAYMENT = "UPDATE_SUPPLIER_PAYMENT";
export const SET_CURRENT_SUPPLIER_PAYMENT = "SET_CURRENT_SUPPLIER_PAYMENT";
export const CLEAR_SUPPLIER_PAYMENT = "CLEAR_SUPPLIER_PAYMENT";
export const DELETE_SUPPLIER_PAYMENT = "DELETE_SUPPLIER_PAYMENT";
export const SUPPLIER_PAYMENT_ERROR = "SUPPLIER_PAYMENT_ERROR";
export const FILTER_SUPPLIER_PAYMENT = "FILTER_SUPPLIER_PAYMENT";
export const TOTAL_PAYABLE = "TOTAL_PAYABLE";
